name: Release Prod
on: workflow_dispatch
jobs:
  call-cdn-upload:
    uses: ./.github/workflows/cdn-upload.yml
    secrets:
      aws_role: ${{ secrets.awsIAMS3UploadRole }}
    with:
      target: "prod"


