name: Release Develop
on:
  push:
    branches:
      - test
jobs:
  call-cdn-upload:
    uses: ./.github/workflows/cdn-upload.yml
    secrets:
      aws_role: ${{ secrets.awsIAMS3UploadDevRole }}
    with:
      target: "dev"
