name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-dependencies-

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
