name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      CC_TEST_REPORTER_ID: 707f5959816d898ffc7176d49d2cd4f6b200c697460965a77d7af28ffdcf5cb6

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-dependencies-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-dependencies-

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: |
          #./cc-test-reporter before-build
          npm run test
          #./cc-test-reporter after-build --exit-code $?
